image: Visual Studio 2017

environment:
  host: x86_64-pc-windows-msvc
  matrix:
    - platform: x86_64
      target: x86_64-pc-windows-msvc
      channel: nightly
    - platform: arm64
      target: aarch64-pc-windows-msvc
      channel: nightly
matrix:
  allow_failures:
    - platform: arm64

install:
    - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
    - appveyor DownloadFile https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win64/nasm-2.14.02-win64.zip -FileName nasm.zip
    - 7z e -y nasm.zip
    - rustup-init -yv --default-toolchain %channel% --default-host %host%
    - set PATH=%PATH%;%USERPROFILE%\.cargo\bin;%APPVEYOR_BUILD_FOLDER%
    - rustc -vV
    - cargo -vV
    - rustup target add %target%

build_script:
    - cargo build --release --target=%target%

artifacts:
    - path: target\$(target)\release\rav1e.lib
      name: librav1e-$(platform)
    - path: include\rav1e.h
      name: librav1e-$(platform)-header

deploy:
  - provider: GitHub
    artifact: librav1e-$(platform)*
    auth_token:
      secure: 'qP65iyZH7HavBuQ8G1XQgkGqJLwdGtV9K5hyqqZavqCm7SakY+tqCwDCRcasSvTg'
    prerelease: true
    on:
      appveyor_repo_tag: true
